version: '3.0'

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    env_file: .env
    restart: on-failure
    expose:     
      - 3306
    volumes:    
      - DB:/var/lib/mysql/
    networks:   
      - NW

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    env_file: .env
    restart: on-failure
    expose:     
      - 9000
    volumes:    
      - WP:/var/www/wordpress
    networks:   
      - NW
    depends_on:  
      - mariadb

  nginx:
    image: nginx
    build: ./requirements/nginx
    restart: on-failure
    ports:      
      - 443:443
    volumes:    
      - WP:/var/www/wordpress
    networks:   
      - NW
    depends_on:  
      - wordpress

volumes:
  DB:
    driver: local
    driver_opts:
      device: /home/taejkim/data/db
      o: bind
      type: none
  WP:
    driver: local
    driver_opts:
      device: /home/taejkim/data/wp
      o: bind
      type: none

networks:
  NW:
    driver: bridge
